### ISSUE TITLE
Run trial of upstream OSEM

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/osem#29]
In [`SeaGL:trial`](https://github.com/SeaGL/osem/tree/trial):

### Resolve outstanding upstream issues

- [x] Explicitly configure database authentication in Docker Compose [#2640](https://github.com/openSUSE/osem/pull/2640)
- [x] Use version range instead of OSEM_RUBY_VERSION. [#2646](https://github.com/openSUSE/osem/pull/2646)
    - [x] Update Ruby dependency: 2.5.8 → 2.5.9 (patch) [#2772](https://github.com/openSUSE/osem/pull/2772)
- [x] Install missing test dependency in base image [#2647](https://github.com/openSUSE/osem/pull/2647)
- [x] Resolve conflict between WebMock and Webdrivers [#2648](https://github.com/openSUSE/osem/pull/2648)
- [x] Work around ChromeDriver/Chromium crash [#2649](https://github.com/openSUSE/osem/pull/2649)
- [x] Decouple tests from unspecified data ordering [#2650](https://github.com/openSUSE/osem/pull/2650), [#2652](https://github.com/openSUSE/osem/pull/2652)
- [x] Fix access to the version history of organization-level roles [#2654](https://github.com/openSUSE/osem/pull/2654)
- [x] Ignore schema.rb in RuboCop [#2655](https://github.com/openSUSE/osem/pull/2655)
- [x] Fix bug in UserDatatable query affecting PostgreSQL [#2656](https://github.com/openSUSE/osem/pull/2656)
- [x] Remove superfluous click to display Markdown editor [#2657](https://github.com/openSUSE/osem/pull/2657)
- [x] Fix bug in logging of screenshots of failed tests [#2658](https://github.com/openSUSE/osem/pull/2658)
- [x] Use Rails transactional tests [#2659](https://github.com/openSUSE/osem/pull/2659)
- [ ] Various inconsistencies in time zone handling (needs review)
- [ ] Various bugs in client-side scripts (needs review)
- [x] Fix bug in test of animated form [#2662](https://github.com/openSUSE/osem/pull/2662)
- [x] Update Docker Compose file format: 2.0 → 2.4 (minor) [#2663](https://github.com/openSUSE/osem/pull/2663)
- [x] Annotate past migrations with Rails version [#2665](https://github.com/openSUSE/osem/pull/2665)
- [x] Fix migration that fails on conferences without pictures [#2666](https://github.com/openSUSE/osem/pull/2666)
- [x] Work around bug in migrations to non-null columns [#2667](https://github.com/openSUSE/osem/pull/2667)
- [x] Serve precompiled assets in example Docker Compose configuration [#2673](https://github.com/openSUSE/osem/pull/2673)
- [x] Stabilize Docker base image [#2697](https://github.com/openSUSE/osem/pull/2697)
- [x] Allow leaving OSEM_SMTP_DOMAIN unset [#2702](https://github.com/openSUSE/osem/pull/2702)
- [x] Remove race condition in test of splash page versioning [#2703](https://github.com/openSUSE/osem/pull/2703)
    - [x] Restore test of splashpage revision history [#2967](https://github.com/openSUSE/osem/pull/2967)
- [x] Correct base image in production Dockerfile [#2773](https://github.com/openSUSE/osem/pull/2773)
- [x] Add missing dependencies to production Docker image [#2774](https://github.com/openSUSE/osem/pull/2774)
- [x] Exclude additional files from Docker images [#2775](https://github.com/openSUSE/osem/pull/2775)
- [x] Correct test that risked false positives [#2776](https://github.com/openSUSE/osem/pull/2776)
- [x] Use be_successful instead of be_success [#2912](https://github.com/openSUSE/osem/pull/2912)
- [x] Update venue country name for Countries 4.2 [#2962](https://github.com/openSUSE/osem/pull/2962)
- [x] Update UserDatatable for ajax-datatables-rails 1 [#2963](https://github.com/openSUSE/osem/pull/2963)
- [x] Update tests of splashpage forms [#2964](https://github.com/openSUSE/osem/pull/2964)
- [x] Fix bug in which role assignments aren’t tracked in version history [#2965](https://github.com/openSUSE/osem/pull/2965)
- [x] Basic feature test of survey creation and response [#2969](https://github.com/openSUSE/osem/pull/2969)
- [ ] Confusion with "complete your proposal" [#1544](https://github.com/openSUSE/osem/issues/1544)

### Audit upstream migrations

Will the migration correctly handle our existing data?

- [x] 2016-06-27 Create surveys `20160627122446`
- [x] 2016-06-28 Create survey questions `20160628093634`
- [x] 2016-06-29 Add target to surveys `20160629145954`
- [x] 2016-06-30 Create survey replies `20160630094850`
- [x] 2016-06-30 Create survey submissions `20160630130731`
- [x] 2016-12-29 Add comments count to events `20161229080315`
- [x] 2017-01-08 Add default to revision in conference `20170108053041`
- [x] 2017-02-12 Add enabled to event schedules `20170212145523`
- [x] 2017-05-16 Create booths `20170516190048`
- [x] 2017-05-30 Add type to cfps `20170530072155`
- [x] 2017-05-30 Create booth requests `20170530112510`
- [x] 2017-06-03 Create physical tickets `20170603095900`
- [x] 2017-06-29 Add short name to tracks `20170629162450`
- [x] 2017-06-29 Add ticket layout to conferences `20170629232817`
- [x] 2017-07-05 Add state cfp active and submitter reference to tracks `20170705075039`
- [x] 2017-07-11 Create ticket scannings `20170711102511`
- [x] 2017-07-12 Add room and dates to tracks `20170712120556`
- [x] 2017-07-15 Make track state not null and add default value `20170715131706`
    - openSUSE/osem#2667
- [x] 2017-07-20 Make track cfp active not null `20170720134353`
    - openSUSE/osem#2667
- [x] 2017-07-21 Add index to physical tickets `20170721001700`
- [x] 2017-07-21 Add custom domain to conferences `20170721184810`
- [x] 2017-07-26 Add relevance to tracks `20170726065629`
- [x] 2017-07-27 Add include booths to splashpages `20170727081731`
- [x] 2017-07-28 Add booth limit to conferences `20170728182033`
- [x] 2017-07-31 Add booths to email settings `20170731161207`
- [x] 2017-08-07 Add registration ticket to tickets `20170807092805`
- [x] 2017-08-09 Add track reference to schedule `20170809120927`
- [x] 2017-08-14 Add selected schedule to tracks `20170814174637`
- [x] 2017-09-05 Add description to cfps `20170905110034`
- [x] 2017-09-24 Add amount paid to ticket purchases `20170924190528`
- [x] 2017-11-18 Change visit id type of ahoy events to integer `20171118113113`
- [x] 2017-11-30 Rebuild conference pictures `20171130172334`
    - openSUSE/osem#2666
- [x] 2017-12-01 Add mastodon to contact `20171201163628`
- [x] 2018-02-26 Add created at and updated at to event types `20180226032958`
- [x] 2018-03-12 Create ahoy visits and events `20180312100045`
- [x] 2018-03-13 Add timestamps to tickets `20180313012253`
- [x] 2018-03-16 Add code of conduct to organization `20180316185150`
- [x] 2018-03-16 Add accepted code of conduct to registrations `20180316220446`
- [x] 2018-08-22 Add submitted proposal attributes in email settings `20180822125509`
- [x] 2018-09-24 User email public defaults to false `20180924221715`
- [x] 2018-10-09 Drop ahoy events `20181009000259`
- [x] 2018-10-17 Add allow reservations on cfps `20181017183243`
- [x] 2018-11-13 Add youtube and blog to contacts `20181113195810`
- [x] 2018-12-29 Remove arrival departure from registrations `20181229233811`
- [x] 2020-03-31 Add organization to versions `20200331214534`
    - openSUSE/osem#2654

### Review local migrations

Is the migration accounted for and its data represented by an upstream feature?

- [x] 2016-05-01 Add show by default to splashpage [`20160501201606`](https://github.com/SeaGL/osem/blob/main/db/migrate/20160501201606_add_show_by_default_to_splashpage.rb)
    - Rolled back, feature replaced by openSUSE/osem#1994
- [x] 2016-05-08 Add banner to splashpage [`20160508201501`](https://github.com/SeaGL/osem/blob/main/db/migrate/20160508201501_add_banner_to_splashpage.rb)
    - Rolled back, feature dropped
- [x] 2016-05-12 Add banner attribution to splashpage [`20160512035046`](https://github.com/SeaGL/osem/blob/main/db/migrate/20160512035046_add_banner_attribution_to_splashpage.rb)
    - Rolled back, feature dropped
- [x] 2017-06-13 Add diversity to events [`20170613224853`](https://github.com/SeaGL/osem/blob/main/db/migrate/20170613224853_add_diversity_to_events.rb)
    - Converted to surveys [`20220312000831`](https://github.com/SeaGL/osem/blob/trial/db/migrate/20220312000831_convert_proposal_questions_to_surveys.rb)
- [x] 2017-06-14 Add first time to events [`20170614025428`](https://github.com/SeaGL/osem/blob/main/db/migrate/20170614025428_add_first_time_to_events.rb)
    - Converted to surveys [`20220312000831`](https://github.com/SeaGL/osem/blob/trial/db/migrate/20220312000831_convert_proposal_questions_to_surveys.rb)
- [ ] 2018-05-22 Add speaker proposal requirements to programs [`20180522011758`](https://github.com/SeaGL/osem/blob/main/db/migrate/20180522011758_add_speaker_proposal_requirements_to_programs.rb)
    - openSUSE/osem#1544
- [x] 2020-07-10 Add pnw to events [`20200710065434`](https://github.com/SeaGL/osem/blob/main/db/migrate/20200710065434_add_pnw_to_events.rb)
    - Converted to surveys [`20220312000831`](https://github.com/SeaGL/osem/blob/trial/db/migrate/20220312000831_convert_proposal_questions_to_surveys.rb)

### Review local commits

Are the needs that led to the commit met upstream?

- [x] 2016-05-07 add config files from server to repo [`ea439e9a`](https://github.com/SeaGL/osem/commit/ea439e9aab1e3bc7789195ca579520ae7bb77641)
- [x] 2016-05-07 remove example configs and add database and secrets config [`f1a1d136`](https://github.com/SeaGL/osem/commit/f1a1d136ed150c05f39b11c5e7b6ef89a4308654)
    - [x] 2016-05-07 fix missing brackets in secrets.yml [`6d674314`](https://github.com/SeaGL/osem/commit/6d67431427ceb5a247079dbae96ed13c33c8f99b)
- [x] 2016-05-07 move devise secret key from secrets.yml to devise init file [`2a141268`](https://github.com/SeaGL/osem/commit/2a141268fe5e5d34a78cb8f96a7923082c8edb60)
- [x] 2016-05-07 remove devise secret [`199eb458`](https://github.com/SeaGL/osem/commit/199eb45885e8b3cbe34ccbf8720c7482edf681d6)
- [x] 2016-05-07 adapt deploy.rb [`0d272b38`](https://github.com/SeaGL/osem/commit/0d272b38273be138603d6c3e8a649aa2d0f94977)
- [x] 2016-05-07 create tmp shared directory in deploy task [`f426db2d`](https://github.com/SeaGL/osem/commit/f426db2d6cf2113153ed62e02d3dd2a25002d635)
- [x] 2016-05-07 change production log level to debug [`093110d7`](https://github.com/SeaGL/osem/commit/093110d7e6abd58e1d339bfa10dbc2574c1e0af6)
- [x] 2016-05-08 fix public/system directory not created in deploy config [`40f95904`](https://github.com/SeaGL/osem/commit/40f95904885a4d587a2a6710f402c917abb2f179)
- [x] 2016-05-08 refactor smtp config [`c0a17c59`](https://github.com/SeaGL/osem/commit/c0a17c59e82ddc59fd3cde7161433c7dde3465ac)
    - [x] 2020-11-01 Revert "refactor smtp config" [`38cd82ca`](https://github.com/SeaGL/osem/commit/38cd82caf3292287320676047788261b256b9f02)
- [x] 2016-05-08 set mailer default from address and force ssl [`7d9d6e85`](https://github.com/SeaGL/osem/commit/7d9d6e856cbaddca8504f89a21d0457dd8a09e48)
- [x] 2016-05-08 update mailer default from address [`2e65971d`](https://github.com/SeaGL/osem/commit/2e65971dcac853a1a3dd090cc07a299204b98a84)
- [x] 2016-05-01 add option to splashpage for it to be shown by default when viewing the conferences index [`985ee40b`](https://github.com/SeaGL/osem/commit/985ee40b48bb4934f3e8cdeef9e5219cdb6b7251)
    - [x] 2016-05-01 add option to splashpage for it to be shown by default when viewing the conferences index [`0bd4d42d`](https://github.com/SeaGL/osem/commit/0bd4d42d2d7d87f4123ce2df4ee4bae6ed9f8c0b)
    - openSUSE/osem#1994
- [x] 2016-05-08 set the navigation background color to the conference color on the splashpage [`a7ef9a78`](https://github.com/SeaGL/osem/commit/a7ef9a7864798fff6239edc94842eb60242e78ee)
- [x] 2016-05-08 add banner image field to splashpages [`d95b82ca`](https://github.com/SeaGL/osem/commit/d95b82cafc9698bf164d16ed7eb5b9a74c2921e5)
    - [x] 2016-05-08 add banner image field to splashpages [`95622106`](https://github.com/SeaGL/osem/commit/956221067dbcb220bd89308c77d6980f8f4f5b62)
    - [x] 2016-05-11 add banner attribution field to footer [`7ec4b6b4`](https://github.com/SeaGL/osem/commit/7ec4b6b4fc6fc15104c526eedef30c41fe7585f8)
    - [x] 2016-05-11 add label to banner field on spalshpage edit form [`47928641`](https://github.com/SeaGL/osem/commit/4792864164d3d1c7cf0d136c61b4f0689203888e)
- [x] 2016-06-28 change smtp relay to gmail [`dc309548`](https://github.com/SeaGL/osem/commit/dc3095485a9c1eb2876773e2dea100a9a517be12)
- [x] 2016-07-06 re-add rvm use task to deploy config [`07327405`](https://github.com/SeaGL/osem/commit/073274056b03a6625b4323fcf881edb0bd4a6cb6)
- [x] 2016-07-06 remove config/database.yml from shared paths in deploy config [`91b33b5e`](https://github.com/SeaGL/osem/commit/91b33b5e6b71b5c57c3a282c506a6265cef8662f)
- [x] 2016-08-18 add delayed job workoff to schedule [`f2dbbfad`](https://github.com/SeaGL/osem/commit/f2dbbfada96315c605ae9142c695d4efbb2d9bfe)
- [x] 2016-09-03 check for possible nil event ratings [`3b3d6515`](https://github.com/SeaGL/osem/commit/3b3d6515e24c6d98d44d249c4fbcd078cee12f95)
    - [x] 2016-09-03 Revert "check for possible nil event ratings" [`ad625c88`](https://github.com/SeaGL/osem/commit/ad625c88df7427d7fc413df11e0b9c21636fe01c)
- [x] 2016-09-18 remove speaker email and blank info items from proposal show page [`786a7132`](https://github.com/SeaGL/osem/commit/786a71325950e8080d6a4499797e8d4b79d13659)
    - [x] 2019-10-11 delete line that displays speaker email [`a0da8886`](https://github.com/SeaGL/osem/commit/a0da8886402c2222f4439a8aa3b4ca48019984e8)
    - [x] 2019-10-11 fixed incorrect haml commenting syntax [`82210aba`](https://github.com/SeaGL/osem/commit/82210aba41b38c3d201a7595e2e6434800442183)
    - openSUSE/osem#1790
- [x] 2016-09-19 sort rooms by name on schedule page and adjust schedule end time [`bf3be566`](https://github.com/SeaGL/osem/commit/bf3be566cd5592c5f808c79c94b1bdcc88d2fb03)
    - openSUSE/osem#2913
- [x] 2016-09-28 reduce font size of speaker biography on proposal show page [`940d1441`](https://github.com/SeaGL/osem/commit/940d14418e9e80dd8446d86e81f55be15c93dadb)
- [x] 2016-11-10 adjust schedule end time [`fd652cf7`](https://github.com/SeaGL/osem/commit/fd652cf7f7a979483e9ae6fe28ca80b78c004c55)
    - openSUSE/osem#1143
- [x] 2017-06-05 Note that DB needs an initial deployment before starting server [`8e1d9fca`](https://github.com/SeaGL/osem/commit/8e1d9fcab6ee1d8f164a9ed5cc1c37045916e9ce)
- [x] 2017-06-05 Update subsequent list numbers [`bb42576e`](https://github.com/SeaGL/osem/commit/bb42576eae03511b4e0ac6d4a40eb52942a8c84a)
- [x] 2017-06-13 Add diversity checkbox [`213c7987`](https://github.com/SeaGL/osem/commit/213c79876dd1ae13f95fe45c206665e8c7e7ede4), Add 'first time speaking' checkbox to proposal form [`951f9e57`](https://github.com/SeaGL/osem/commit/951f9e57a81f6d64f5fff365d1b419c3d9f83477)
    - [x] 2018-05-23 Permit diversity param [`1e4a60df`](https://github.com/SeaGL/osem/commit/1e4a60dfa2a73eca93d02cfc20e5b905fb1abfcf)
    - [x] 2018-05-25 Permit first_time param [`f06b0c25`](https://github.com/SeaGL/osem/commit/f06b0c2507968a74855afe32b9e27c24215ecd99)
    - [x] 2017-07-25 This adds in the donut graphs for first-time and diversity numbers [`e7192150`](https://github.com/SeaGL/osem/commit/e7192150a75403afffc57fefcb7cce802dddabf1)
    - [x] 2018-05-23 Query for diversity stats as boolean [`659e12e9`](https://github.com/SeaGL/osem/commit/659e12e9e9bed6d768d40dcd52a437add76eca6b)
    - [x] 2018-05-25 Query for first time stats as boolean [`0c336e55`](https://github.com/SeaGL/osem/commit/0c336e5524cbb73f428b70fa0829d783c6fb59e8)
    - [x] 2020-07-10 Allow editing of diversity & first-time responses [`a1ef411d`](https://github.com/SeaGL/osem/commit/a1ef411d6558742aba0836f95127aaffe443aba4)
    - [x] 2020-07-10 Add PNW checkbox to event proposal form [`a99c9353`](https://github.com/SeaGL/osem/commit/a99c9353165950024e9538bd48b71f970074e4d6)
    - openSUSE/osem#3058
- [x] 2017-06-17 Update deployment for mira 1.0 [`11c02be2`](https://github.com/SeaGL/osem/commit/11c02be2f1133768bfd147ce9800007e0dfcccaa)
    - [x] 2020-09-29 Revert "Update deployment for mira 1.0" [`4e15c6f4`](https://github.com/SeaGL/osem/commit/4e15c6f438276bc6a6fbd548224cf000fe2b97c5)
- [x] 2017-06-17 mira is not finding ruby right for the jobs, hardcode for testing [`9aeeb73b`](https://github.com/SeaGL/osem/commit/9aeeb73ba0e1102fc14169c70c54858e21b97704)
- [x] 2017-06-17 Try bundle exec [`ead7993a`](https://github.com/SeaGL/osem/commit/ead7993a04f0b0a1c35ae1f7e495b324474d937f)
- [x] 2017-06-17 Force success [`84acd254`](https://github.com/SeaGL/osem/commit/84acd25491edc1d40a2a2798f3603ff2fd3e2126)
- [x] 2017-06-17 Disable starting delayed_jobs [`7263e2a9`](https://github.com/SeaGL/osem/commit/7263e2a97bf70b243b99b03623aa9e4f98460167)
- [x] 2017-06-17 Fix syntax on markdown hint [`c98c2d46`](https://github.com/SeaGL/osem/commit/c98c2d46cda5151cad5979e8efd772743551e935)
- [x] 2017-08-14 Disable the comment notification emails for now [`a09eb20c`](https://github.com/SeaGL/osem/commit/a09eb20cfa6f5ad75de8ace295672521e6bdf111)
    - openSUSE/osem#3059
- [x] 2017-12-23 Add in a js engine for uglifier [`d7de0a09`](https://github.com/SeaGL/osem/commit/d7de0a0945a9fa452e9adac60a657c973be04ead)
- [x] 2017-12-23 Update gemfile.lock [`2630cbc1`](https://github.com/SeaGL/osem/commit/2630cbc18afcd74f883531115c69d9dafa5c4554)
- [x] 2017-12-23 WIP to deploy to EC2/RDS [`1227a194`](https://github.com/SeaGL/osem/commit/1227a194afaf3123a5589cf095a48f9357ee5cee)
- [x] 2018-05-05 WIP to deploy to EC2/RDS [`ead64295`](https://github.com/SeaGL/osem/commit/ead64295a28a7592925cba5c9fe76824197dfe91)
- [x] 2018-05-05 Update vagrant file [`16ea63a2`](https://github.com/SeaGL/osem/commit/16ea63a2d7ed3d4e890f180c319823d6db06e476)
- [x] 2018-05-05 update bootstrap [`fd03ca14`](https://github.com/SeaGL/osem/commit/fd03ca14624339d5206e2dc2bd466bc35a874a20)
- [ ] 2018-05-24 Add extra toggles for speaker reminders to CFP settings [`c7ca33a8`](https://github.com/SeaGL/osem/commit/c7ca33a87e2dd3b15220a91b240860c999eccae4)
    - [ ] 2018-05-24 Only ask speakers to do what the CFP settings ask for [`aa830196`](https://github.com/SeaGL/osem/commit/aa830196ac228d66f1c652c2316dff8ebcd50117)
    - [ ] 2018-06-02 refactor admin CFPs show page a little bit to be more readable [`6b36d3af`](https://github.com/SeaGL/osem/commit/6b36d3af78ec2f0f0abe0cdead7e2d3efdec4742)
    - [ ] 2021-06-13 Fix bug preventing the creation of CFPs [`d44be857`](https://github.com/SeaGL/osem/commit/d44be857df3e6360abc9aefe1dde74b57bb3e212)
    - [ ] 2021-06-13 Fix bug preventing the display of CFP options [`d613080d`](https://github.com/SeaGL/osem/commit/d613080d1b0d262c72a25a05269242fbcdf99af1)
    - openSUSE/osem#1544
- [x] 2020-07-10 Use Docker Compose instead of Vagrant [`e50ecbbb`](https://github.com/SeaGL/osem/commit/e50ecbbbf7b6980dd914e9aa63177d2984dc1b49)
- [x] 2020-07-10 Update deployment configuration [`42609fdd`](https://github.com/SeaGL/osem/commit/42609fdd56e5386cd343e3b2fde84b6ea4bab163)
- [x] 2020-07-10 Fix bug in Docker Compose configuration [`997dc3a7`](https://github.com/SeaGL/osem/commit/997dc3a717768e160bd27ebc159723fc71876f49)
- [x] 2020-07-10 Update RSpec [`732e9961`](https://github.com/SeaGL/osem/commit/732e99618b920dcb6d9b88cf82ed682384b869b1)
- [x] 2020-08-05 Update edit.html.haml [`8fb4ca13`](https://github.com/SeaGL/osem/commit/8fb4ca13aa53d58614e2cc8f5223079b2e9dd12c)
    - [x] 2020-08-08 Revert "Update edit.html.haml" [`fd2cb24d`](https://github.com/SeaGL/osem/commit/fd2cb24d15a9be8cfadc3c5f114efc2f178fbf03)
    - [ ] 2020-08-08 After registration, show home page instead of account edit screen. [`9340939b`](https://github.com/SeaGL/osem/commit/9340939bfeabb30c82d82723df6f3ed7cc0eabfc)
- [ ] 2020-08-10 Add CFP Respondents metric to conference dashboard [`8ceabe92`](https://github.com/SeaGL/osem/commit/8ceabe92a54533d947935769dc56f3415612bdc0)
- [x] 2020-09-30 Use systemd in deploy script [`f3259b30`](https://github.com/SeaGL/osem/commit/f3259b30b58c10d6c0dd630e084694fc37d350be)
- [ ] 2020-09-30 Manage Delayed::Job via systemd [`48435553`](https://github.com/SeaGL/osem/commit/484355539a7a480842b2bcbb53cf75e2daaa25bb)
- [x] 2020-10-31 Correct development documentation [`7a8d47af`](https://github.com/SeaGL/osem/commit/7a8d47af130e77299b281a417f3c376ad5b5b06d)
- [x] 2020-10-31 Update dependencies with failing native extensions [`9336d0dd`](https://github.com/SeaGL/osem/commit/9336d0dd5a5b4c6f1b85e79fe859671b089dce28)
- [x] 2020-11-01 Configure RuboCop for supported Ruby version [`304da8f2`](https://github.com/SeaGL/osem/commit/304da8f24db258ea3400689dbc65f7865f2ff8cd)
- [x] 2020-11-01 Remove hard-coded email configuration [`af45e6ff`](https://github.com/SeaGL/osem/commit/af45e6ff3c4103c8837c42abad8ab1cb378585c6)
- [x] 2020-11-02 Omit nil SMTP settings [`37713ca5`](https://github.com/SeaGL/osem/commit/37713ca594b0583066df13747b15db82147a3b38)
    - openSUSE/osem#2702
- [ ] 2020-11-02 Begin API v2 using existing JSON:API capability [`efc0d3c8`](https://github.com/SeaGL/osem/commit/efc0d3c8c46a8dd5566c9ceacfe9853ddc76a04c)
    - [ ] 2020-11-01 Configure the default origin for absolute URLs [`4f36cd21`](https://github.com/SeaGL/osem/commit/4f36cd21cb79ac7ec552b8d60ddaead2dd43e86e)
    - [ ] 2020-10-31 Update ActiveModelSerializers and namespace API v1 serializers [`5dadb162`](https://github.com/SeaGL/osem/commit/5dadb1627f1a64054a64c25060313b2bcc774810)
    - [ ] 2020-11-03 Fix bug in API v2 time zones [`0b50b997`](https://github.com/SeaGL/osem/commit/0b50b9976494d06b64cadda61e86714473a6040d)
    - [ ] 2020-11-12 Add permissive CORS policy to v2 API [`86a03a3e`](https://github.com/SeaGL/osem/commit/86a03a3e01cee731de973e9daee64ad985873761)
- [x] 2021-06-12 Update mimemagic [`e0c5646b`](https://github.com/SeaGL/osem/commit/e0c5646bec9a134b3b2876435a80825931343d7a)
    - openSUSE/osem#2745

**Comment by AndrewKvalheim** [comment]
We’ve deemed this complete enough and have migrated to a [transitional fork](https://github.com/SeaGL/osem/tree/interim#readme), leaving the outstanding items to be resolved separately as needed.
